### ISSUE TITLE
What is the right defconfig file to build the kernel?

### ISSUE THREAD

**Issue by VTVishwanath** [improbir/kernel_realme_sdm710#1]
I see many defconfig files [under](https://github.com/improbir/kernel_realme_sdm710/tree/13/arch/arm64/configs) but which one is the right one to build for **RMX1851 (Realme 3 pro having sdm710 chipset)**. 

Other kernel sources has defconfig under the same path called **lineageos_RMX1851_defconfig** [like this one](https://github.com/Cykeek/kernel_realme_sdm710/tree/A13/arch/arm64/configs )

I have checked multiple branches like 13 and 14 both don't have **lineageos_RMX1851_defconfig** file.

Which one is the right defconfig file for RMX1851 device?

**Comment by improbir** [comment]
> I see many defconfig files [under](https://github.com/improbir/kernel_realme_sdm710/tree/13/arch/arm64/configs) but which one is the right one to build for **RMX1851 (Realme 3 pro having sdm710 chipset)**.
> 
> Other kernel sources has defconfig under the same path called **lineageos_RMX1851_defconfig** [like this one](https://github.com/Cykeek/kernel_realme_sdm710/tree/A13/arch/arm64/configs)
> 
> I have checked multiple branches like 13 and 14 both don't have **lineageos_RMX1851_defconfig** file.
> 
> Which one is the right defconfig file for RMX1851 device?

sdm670-perf_defconfig or you can inherit your custom defconfig

**Comment by VTVishwanath** [comment]
Does the sdm670-perf_defconfig work for sdm710? what's the difference between all these defconfigs?

Also, what do you mean by I can inherit my own custom defconfig? How can I do that?
Do you have any steps to do the same?
